default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: blogstrap_development
  host: 191.101.70.50
  port: 5432
  username: postgres
  password: Fabio1982Mattes
  min_messages: log

test:
  <<: *default
  database: blogstrap_test
  host: 191.101.70.50
  port: 5432
  username: postgres
  password: Fabio1982Mattes
  min_messages: log

production:
  <<: *default
  database: blogstrap
  host: 191.101.70.50
  port: 5432
  username: postgres
  password: Fabio1982Mattes
  min_messages: log
